startPositions:
  - x: 1500
    y: 150
    z: 0
    world: 'world'
parkourBlocks:
  - 'EMERALD_BLOCK'
runFinishCommands: false
finishCommands:
  - commands:
      - '/say {{playerName}} is NOOB with score {{score}}'
    maxScore: 5
  - commands:
      - '/say {{playerName}} is JUMPER with score {{score}}'
    minScore: 6
    maxScore: 10
  - commands:
      - '/say {{playerName}} is MONSTER with score {{score}}'
    minScore: 11
particle:
  show: false
  type: CLOUD
  amount: 50
permissions:
  openGui: 'infinityparkour.opengui'
  leaveArena: 'infinityparkour.leavearena'
  playGame: 'infinityparkour.play'
  reload: 'infinityparkour.reload'