startPositions:
  - x: 1500
    y: 100
    z: 0
    world: 'world'
parkourBlock: 'WHITE_TERRACOTTA'
runFinishCommand: false
finishCommand: '/say {{playerName}} achieved score {{score}}'
permissions:
  openGui: 'infinityparkour.opengui'
  leaveArena: 'infinityparkour.leavearena'
  playGame: 'infinityparkour.play'
  reload: 'infinityparkour.reload'